/**
 * Build step — resolves LSP binary path and compiles the binary.
 *
 * Usage:
 *   deno task compile                          # defaults to 'deno lsp'
 *   deno task compile 'deno lsp'               # explicit
 *   deno task compile 'typescript-language-server --stdio'
 */
const lspCommand = Deno.args[0] ?? "deno lsp";
const parts = lspCommand.split(/\s+/);
const binary = parts[0];
const args = parts.slice(1);

// Resolve binary to absolute path
const { stdout, code } = new Deno.Command("which", {
  args: [binary],
  stdout: "piped",
}).outputSync();

if (code !== 0) {
  console.error(`Error: could not find '${binary}' on PATH`);
  Deno.exit(1);
}

const resolvedPath = new TextDecoder().decode(stdout).trim();
console.log(`LSP: ${resolvedPath} ${args.join(" ")}`);

// Write config
// Default init options per known LSP server
const initOptions: Record<string, Record<string, unknown>> = {
  deno: { enable: true },
};
const initOpts = initOptions[binary];
const initLine = initOpts
  ? `\n  initializationOptions: ${JSON.stringify(initOpts)},`
  : "";

const content = `// AUTO-GENERATED by build.ts — do not edit
import { z } from "npm:zod";
import type { LspConfig } from "./types.ts";

const LspConfigSchema = z.object({
  command: z.string().min(1),
  args: z.array(z.string()),
  initializationOptions: z.record(z.string(), z.unknown()).optional(),
});

export const LSP_CONFIG: LspConfig = LspConfigSchema.parse({
  command: ${JSON.stringify(resolvedPath)},
  args: ${JSON.stringify(args)},${initLine}
});
`;

Deno.writeTextFileSync("src/core/dto/lsp-config.ts", content);

// Compile
const compile = new Deno.Command("deno", {
  args: ["compile", "--allow-read", "--allow-net", "--allow-env", "--allow-run", "-o", "shape-checker", "main.ts"],
  stdout: "inherit",
  stderr: "inherit",
});

const result = compile.outputSync();
Deno.exit(result.code);
