/**
 * Pre-compile build step — resolves the deno binary path
 * and writes it as a validated DTO for the compiled binary.
 */
const { stdout } = new Deno.Command("which", {
  args: ["deno"],
  stdout: "piped",
}).outputSync();

const denoPath = new TextDecoder().decode(stdout).trim();

if (!denoPath) {
  console.error("Error: could not find deno on PATH");
  Deno.exit(1);
}

const content = `// AUTO-GENERATED by build.ts — do not edit
import { z } from "npm:zod";

export const DenoConfigSchema = z.object({
  denoPath: z.string().min(1),
});

export const DENO_PATH = ${JSON.stringify(denoPath)};

export const denoConfig = DenoConfigSchema.parse({ denoPath: DENO_PATH });
`;

Deno.writeTextFileSync("src/core/dto/deno-config.ts", content);
console.log(`Baked deno path: ${denoPath}`);
