export const DEFAULT_MODEL = "claude-haiku-4-5-20251001";

/**
 * Build step — resolves LSP binary path and generates lsp-config.ts.
 *
 * When run directly:
 *   deno run --allow-read --allow-run --allow-write src/bootstrap/config.ts
 *   deno run --allow-read --allow-run --allow-write src/bootstrap/config.ts 'deno lsp'
 *   deno run --allow-read --allow-run --allow-write src/bootstrap/config.ts 'typescript-language-server --stdio'
 */
if (import.meta.main) {
  const lspCommand = Deno.args[0] ?? "deno lsp";
  const parts = lspCommand.split(/\s+/);
  const binary = parts[0];
  const args = parts.slice(1);

  const { stdout, code } = new Deno.Command("which", {
    args: [binary],
    stdout: "piped",
  }).outputSync();

  if (code !== 0) {
    console.error(`Error: could not find '${binary}' on PATH`);
    Deno.exit(1);
  }

  const resolvedPath = new TextDecoder().decode(stdout).trim();
  console.log(`LSP: ${resolvedPath} ${args.join(" ")} (using bare name "${binary}" for portability)`);

  const initOptions: Record<string, Record<string, unknown>> = {
    deno: { enable: true },
  };
  const initOpts = initOptions[binary];
  const initLine = initOpts
    ? `\n  initializationOptions: ${JSON.stringify(initOpts)},`
    : "";

  const content = `// AUTO-GENERATED by config.ts — do not edit
import { z } from "#zod";
import type { LspConfig } from "./types.ts";

const LspConfigSchema = z.object({
  command: z.string().min(1),
  args: z.array(z.string()),
  initializationOptions: z.record(z.string(), z.unknown()).optional(),
});

export const LSP_CONFIG: LspConfig = LspConfigSchema.parse({
  command: ${JSON.stringify(binary)},
  args: ${JSON.stringify(args)},${initLine}
});
`;

  Deno.writeTextFileSync("src/core/dto/lsp-config.ts", content);
}
